### ISSUE TITLE
No chapter marks on downloaded Storytel mp3 

### ISSUE THREAD

**Issue by masteoo** [jo1gi/audiobook-dl#66]
Hello, sorry, in Storytel downloaded mp3 files there are no chapter marks (I tried different players) even if during the execution of the script I read:
'...
adding chapters
adding cover...'
so I think that metadata should all be saved in the final mp3.. thanks

**Comment by nonab** [comment]
i did a little debug and it seems that chapter times are correct

` INFO Adding chapters
DEBUG Chapter start: 0
DEBUG Chapter end: 16000
DEBUG Chapter start: 16000
DEBUG Chapter end: 28000
DEBUG Chapter start: 28000
DEBUG Chapter end: 713000
DEBUG Chapter start: 713000
DEBUG Chapter end: 1980000
DEBUG Chapter start: 1980000
DEBUG Chapter end: 3460000
DEBUG Chapter start: 3460000
DEBUG Chapter end: 4673000
DEBUG Chapter start: 4673000
DEBUG Chapter end: 6082000
DEBUG Chapter start: 6082000
DEBUG Chapter end: 7360000
DEBUG Chapter start: 7360000
DEBUG Chapter end: 9128000
DEBUG Chapter start: 9128000
DEBUG Chapter end: 10442000
DEBUG Chapter start: 10442000
DEBUG Chapter end: 11951000
DEBUG Chapter start: 11951000
DEBUG Chapter start: 19044000
DEBUG Chapter end: 19435000
DEBUG Chapter start: 19435000
DEBUG Chapter end: 20794000
DEBUG Chapter start: 20794000
DEBUG Chapter end: 21184000
DEBUG Chapter start: 21184000
DEBUG Chapter end: 22084000
DEBUG Chapter start: 22084000
DEBUG Chapter end: 22544000
 INFO Adding metadata
`
however when i tried to list them with mp3chaps i get something like this

`PS D:\Temp\python\audiobook-dl-0.7.0> mp3chaps -i .\test.mp3         
Chapters:
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
`
i don't know if it's a good way to check because when i tried adding chapters with the same tool they still don't show up in foobar

**Comment by masteoo** [comment]
> i did a little debug and it seems that chapter times are correct
> 
> `INFO Adding chapters DEBUG Chapter start: 0 DEBUG Chapter end: 16000 DEBUG Chapter start: 16000 DEBUG Chapter end: 28000 DEBUG Chapter start: 28000 DEBUG Chapter end: 713000 DEBUG Chapter start: 713000 DEBUG Chapter end: 1980000 DEBUG Chapter start: 1980000 DEBUG Chapter end: 3460000 DEBUG Chapter start: 3460000 DEBUG Chapter end: 4673000 DEBUG Chapter start: 4673000 DEBUG Chapter end: 6082000 DEBUG Chapter start: 6082000 DEBUG Chapter end: 7360000 DEBUG Chapter start: 7360000 DEBUG Chapter end: 9128000 DEBUG Chapter start: 9128000 DEBUG Chapter end: 10442000 DEBUG Chapter start: 10442000 DEBUG Chapter end: 11951000 DEBUG Chapter start: 11951000 DEBUG Chapter start: 19044000 DEBUG Chapter end: 19435000 DEBUG Chapter start: 19435000 DEBUG Chapter end: 20794000 DEBUG Chapter start: 20794000 DEBUG Chapter end: 21184000 DEBUG Chapter start: 21184000 DEBUG Chapter end: 22084000 DEBUG Chapter start: 22084000 DEBUG Chapter end: 22544000 INFO Adding metadata` however when i tried to list them with mp3chaps i get something like this
> 
> `PS D:\Temp\python\audiobook-dl-0.7.0> mp3chaps -i .\test.mp3 Chapters: None None None None None None None None None None None None None None None None None None None None ` i don't know if it's a good way to check because when i tried adding chapters with the same tool they still don't show up in foobar

@nonab Hello, thanks for your feedback, sorry I'm not a programmer:( but when I play all my downloaded mp3 with Vlc or other players there are no chapters, but other mp3 downloaded from internet have chapters, so I think there is something wrong

**Comment by masteoo** [comment]
> > @nonab Hello, thanks for your feedback, sorry I'm not a programmer:( but when I play all my Storytel downloaded mp3 with Vlc or other players there are no chapters, but other mp3 downloaded from internet have chapters, so I think there is something wrong
> 
> Can you give me example mp3 file with chapters? That would help.

Ok I'll see what I can find

**Comment by masteoo** [comment]
> > @nonab Hello, thanks for your feedback, sorry I'm not a programmer:( but when I play all my Storytel downloaded mp3 with Vlc or other players there are no chapters, but other mp3 downloaded from internet have chapters, so I think there is something wrong
> 
> Can you give me example mp3 file with chapters? That would help.

Hello, I read this comment https://github.com/dskrad/mp3chaps/issues/16 so I tried to play my mp3 with mpv player and chapters are ok..so is vlc problem🤔? I use only vlc payer:(
[Sherlock Holmes e un caso d'identità (1).zip](https://github.com/jo1gi/audiobook-dl/files/13353548/Sherlock.Holmes.e.un.caso.d.identita.1.zip)

**Comment by masteoo** [comment]
> The chapters were added, but they were set to `None` if they didn't have any title. I have fixed that now. I don't know why vlc doesn't show them.

@jo1gi 
Thanks for your support. So I just need to update the script on my Termux app with _pkg upgrade audiobook-dl_ line? Thanks

**Comment by masteoo** [comment]
@jo1gi ok I try, thanks for your support
